### ISSUE TITLE
Wrong media hash

### ISSUE THREAD

**Issue by zack9433** [wanasit/enml-js#1]
Following is my test file:

{
  "guid": "4fa776ce-be89-4715-8b78-13c687fb62be",
  "title": "無標題",
  "content": "<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/></head><body style=\"word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;\"><div>\n<div><br clear=\"none\"/></div>\n<div>\n<div><img alt=\"Evernote Logo\" hash=\"4914ced8925f9adcc1c58ab87813c81f\" type=\"image/png\"/>\n<h1> </h1>\n</div>\n</div>\n</div></body></html>",
    "contentHash": "l\u000b�T#���\u0003\fH\u001b��a�",
  "contentLength": 301,
  "created": 1356396242000,
  "updated": 1356400484000,
  "deleted": null,
  "active": true,
  "updateSequenceNum": 85,
  "notebookGuid": "a69f2542-0630-439f-ae75-2c115e9b9146",
  "tagGuids": null,
  "resources": [
      {
        "guid": "697af336-7530-4de7-ab70-e253afb650c0",
        "noteGuid": "4fa776ce-be89-4715-8b78-13c687fb62be",
        "data": {
                "bodyHash": "I\u0014�ؒ_���Ŋ�x\u0013�\u001f",
                "size": 2176,
                "body": null
              },
        "mime": "image/png",
        "width": 215,
        "height": 54,
        "duration": null,
        "active": true,
        "recognition": {
                "bodyHash": "�X�Q��\u00153\u0002�ۖRh\u0010�",
                "size": 411,
                "body": null
              },
        "attributes": {
                "sourceURL": null,
                "timestamp": null,
                "latitude": null,
                "longitude": null,
                "altitude": null,
                "cameraMake": null,
                "cameraModel": null,
                "clientWillIndex": null,
                "recoType": null,
                "fileName": null,
                "attachment": null
              },
        "updateSequenceNum": 86,
        "alternateData": null
      }
    ],
  "attributes": {
      "subjectDate": null,
      "latitude": null,
      "longitude": null,
      "altitude": null,
      "author": null,
      "source": null,
      "sourceURL": null,
      "sourceApplication": null,
      "shareDate": null
    },
  "tagNames": null
}

The output did not change from hash to source.

================ Example 2 (ENML) ================
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/></head><body style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;"><div>

<div><br clear="none"/></div>

<div>
<div><img alt="Evernote Logo" hash="4914ced8925f9adcc1c58ab87813c81f" type="image/png"/>
<h1> </h1>
</div>

</div>
</div></body></html>
================ Example 2 (HTML) ================
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/></head><body style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;"><div>

<div><br clear="none"/></div>

<div>
<div><img alt="Evernote Logo" hash="4914ced8925f9adcc1c58ab87813c81f" type="image/png"/>
<h1> </h1>
</div>

</div>
</div></body></html>

**Comment by phuoc-insignia** [comment]
I'm able to render the image with this PR
https://github.com/wanasit/enml-js/pull/16
