### ISSUE TITLE
enml.URLOfResource not defined

### ISSUE THREAD

**Issue by marcucio** [wanasit/enml-js#14]
using your browser example I get the following:

enml.URLOfResource not defined

I also don't see this function defined in enml.js

**Comment by bosslee** [comment]
Hi @marcucio 

I having the same issue and I was wondering if you manage to find a fix for it?

Thank you :D

**Comment by marcucio** [comment]
I got the resources from the server and just did:
var html = enml.HTMLOfENML(content, resources);
The example is incorrect, that function doesn't exist

**Comment by bosslee** [comment]
Thanks @marcucio 
I tried to do the same the but images not showing. Maybe I can put the question up on stackoverflow and we discuss there :D 
Because might not be good to use issue for me to ask question, worry that the repo owner might not happy :+1:

**Comment by wanasit** [comment]
I'm very sorry for my slow response.

I just realized that the code in example folder is outdated. You cannot use function like URLOfResource.
The only information that still correct is the doc in README and the test (test/test.spec.js).

I haven't developed any app for Evernote for a while. Sorry again for my slow response. I will update the example code as soon as possible.

**Comment by bosslee** [comment]
Hi @wanasit 

No problem. Thanks for making the lib.
I was wondering if I can get your email and maybe ask you some questions on the lib?
Or would you like me to put them in issues and label them as questions :D 

Thank you

**Comment by wanasit** [comment]
Sorry that I'm uncomfortable with sharing my email address.
It's better if you can create an issue. Some other people might also find it useful.
